INSERT INTO phpgw_weather_region (region_id,region_name) values (1,'Albanie');
INSERT INTO phpgw_weather_region (region_id,region_name) values (2,'Algeria');
INSERT INTO phpgw_weather_region (region_id,region_name) values (3,'Angola');
INSERT INTO phpgw_weather_region (region_id,region_name) values (4,'Antarctic');
INSERT INTO phpgw_weather_region (region_id,region_name) values (5,'Antigua and Barbuda');
INSERT INTO phpgw_weather_region (region_id,region_name) values (6,'Argentina');
INSERT INTO phpgw_weather_region (region_id,region_name) values (7,'Armenia');
INSERT INTO phpgw_weather_region (region_id,region_name) values (8,'Aruba');
INSERT INTO phpgw_weather_region (region_id,region_name) values (9,'Australia');
INSERT INTO phpgw_weather_region (region_id,region_name) values (10,'Austria');
INSERT INTO phpgw_weather_region (region_id,region_name) values (11,'Azerbaijan');
INSERT INTO phpgw_weather_region (region_id,region_name) values (12,'Bahamas');
INSERT INTO phpgw_weather_region (region_id,region_name) values (13,'Bahrain');
INSERT INTO phpgw_weather_region (region_id,region_name) values (14,'Bangladesh');
INSERT INTO phpgw_weather_region (region_id,region_name) values (15,'Barbados');
INSERT INTO phpgw_weather_region (region_id,region_name) values (16,'Belarus');
INSERT INTO phpgw_weather_region (region_id,region_name) values (17,'Belgium');
INSERT INTO phpgw_weather_region (region_id,region_name) values (18,'Belize');
INSERT INTO phpgw_weather_region (region_id,region_name) values (19,'Benin');
INSERT INTO phpgw_weather_region (region_id,region_name) values (20,'Bermuda');
INSERT INTO phpgw_weather_region (region_id,region_name) values (21,'Bolivia');
INSERT INTO phpgw_weather_region (region_id,region_name) values (22,'Botswana');
INSERT INTO phpgw_weather_region (region_id,region_name) values (23,'Brazil');
INSERT INTO phpgw_weather_region (region_id,region_name) values (24,'British Indian Ocean Territory');
INSERT INTO phpgw_weather_region (region_id,region_name) values (25,'Brunei Darussalam');
INSERT INTO phpgw_weather_region (region_id,region_name) values (26,'Bulgaria');
INSERT INTO phpgw_weather_region (region_id,region_name) values (27,'Burundi');
INSERT INTO phpgw_weather_region (region_id,region_name) values (28,'Cambodia');
INSERT INTO phpgw_weather_region (region_id,region_name) values (29,'Cameroon');
INSERT INTO phpgw_weather_region (region_id,region_name) values (30,'Canada');
INSERT INTO phpgw_weather_region (region_id,region_name) values (31,'Cape Verde');
INSERT INTO phpgw_weather_region (region_id,region_name) values (32,'Cayman Islands');
INSERT INTO phpgw_weather_region (region_id,region_name) values (33,'Central African Republic');
INSERT INTO phpgw_weather_region (region_id,region_name) values (34,'Chad');
INSERT INTO phpgw_weather_region (region_id,region_name) values (35,'Chile');
INSERT INTO phpgw_weather_region (region_id,region_name) values (36,'China');
INSERT INTO phpgw_weather_region (region_id,region_name) values (37,'Christmas Island');
INSERT INTO phpgw_weather_region (region_id,region_name) values (38,'Colombia');
INSERT INTO phpgw_weather_region (region_id,region_name) values (39,'Comoros');
INSERT INTO phpgw_weather_region (region_id,region_name) values (40,'Congo');
INSERT INTO phpgw_weather_region (region_id,region_name) values (41,'Cook Islands');
INSERT INTO phpgw_weather_region (region_id,region_name) values (42,'Costa Rica');
INSERT INTO phpgw_weather_region (region_id,region_name) values (43,'Cote D\'Ivoire');
INSERT INTO phpgw_weather_region (region_id,region_name) values (44,'Croatia');
INSERT INTO phpgw_weather_region (region_id,region_name) values (45,'Cuba');
INSERT INTO phpgw_weather_region (region_id,region_name) values (46,'Cyprus');
INSERT INTO phpgw_weather_region (region_id,region_name) values (47,'Czech Republic');
INSERT INTO phpgw_weather_region (region_id,region_name) values (48,'Denmark');
INSERT INTO phpgw_weather_region (region_id,region_name) values (49,'Djibouti');
INSERT INTO phpgw_weather_region (region_id,region_name) values (50,'Dominica');
INSERT INTO phpgw_weather_region (region_id,region_name) values (51,'Dominican Republic');
INSERT INTO phpgw_weather_region (region_id,region_name) values (52,'Ecuador');
INSERT INTO phpgw_weather_region (region_id,region_name) values (53,'Egypt');
INSERT INTO phpgw_weather_region (region_id,region_name) values (54,'El Salvador');
INSERT INTO phpgw_weather_region (region_id,region_name) values (55,'Ethiopia');
INSERT INTO phpgw_weather_region (region_id,region_name) values (56,'Fiji');
INSERT INTO phpgw_weather_region (region_id,region_name) values (57,'Finland');
INSERT INTO phpgw_weather_region (region_id,region_name) values (58,'France');
INSERT INTO phpgw_weather_region (region_id,region_name) values (59,'French Guiana');
INSERT INTO phpgw_weather_region (region_id,region_name) values (60,'French Polynesia');
INSERT INTO phpgw_weather_region (region_id,region_name) values (61,'Gabon');
INSERT INTO phpgw_weather_region (region_id,region_name) values (62,'Gambia');
INSERT INTO phpgw_weather_region (region_id,region_name) values (63,'Georgia');
INSERT INTO phpgw_weather_region (region_id,region_name) values (64,'Germany');
INSERT INTO phpgw_weather_region (region_id,region_name) values (65,'Ghana');
INSERT INTO phpgw_weather_region (region_id,region_name) values (66,'Gibraltar');
INSERT INTO phpgw_weather_region (region_id,region_name) values (67,'Greece');
INSERT INTO phpgw_weather_region (region_id,region_name) values (68,'Greenland');
INSERT INTO phpgw_weather_region (region_id,region_name) values (69,'Grenada');
INSERT INTO phpgw_weather_region (region_id,region_name) values (70,'Guadeloupe');
INSERT INTO phpgw_weather_region (region_id,region_name) values (71,'Guatemala');
INSERT INTO phpgw_weather_region (region_id,region_name) values (72,'Guinea');
INSERT INTO phpgw_weather_region (region_id,region_name) values (73,'Guinea-Bissau');
INSERT INTO phpgw_weather_region (region_id,region_name) values (74,'Guyana');
INSERT INTO phpgw_weather_region (region_id,region_name) values (75,'Haiti');
INSERT INTO phpgw_weather_region (region_id,region_name) values (76,'Honduras');
INSERT INTO phpgw_weather_region (region_id,region_name) values (77,'Hong Kong');
INSERT INTO phpgw_weather_region (region_id,region_name) values (78,'Hungary');
INSERT INTO phpgw_weather_region (region_id,region_name) values (79,'Iceland');
INSERT INTO phpgw_weather_region (region_id,region_name) values (80,'India');
INSERT INTO phpgw_weather_region (region_id,region_name) values (81,'Indonesia');
INSERT INTO phpgw_weather_region (region_id,region_name) values (82,'Iran, Islamic Republic of');
INSERT INTO phpgw_weather_region (region_id,region_name) values (83,'Ireland');
INSERT INTO phpgw_weather_region (region_id,region_name) values (84,'Israel');
INSERT INTO phpgw_weather_region (region_id,region_name) values (85,'Italy');
INSERT INTO phpgw_weather_region (region_id,region_name) values (86,'Jamaica');
INSERT INTO phpgw_weather_region (region_id,region_name) values (87,'Japan');
INSERT INTO phpgw_weather_region (region_id,region_name) values (88,'Jordan');
INSERT INTO phpgw_weather_region (region_id,region_name) values (89,'Nepal');
INSERT INTO phpgw_weather_region (region_id,region_name) values (90,'Kenya');
INSERT INTO phpgw_weather_region (region_id,region_name) values (91,'Kiribati');
INSERT INTO phpgw_weather_region (region_id,region_name) values (92,'Korea, Democratic People\'s Republic of');
INSERT INTO phpgw_weather_region (region_id,region_name) values (93,'Korea, Republic of');
INSERT INTO phpgw_weather_region (region_id,region_name) values (94,'Kuwait');
INSERT INTO phpgw_weather_region (region_id,region_name) values (95,'Lao People\'s Democratic Republic');
INSERT INTO phpgw_weather_region (region_id,region_name) values (96,'Lebanon');
INSERT INTO phpgw_weather_region (region_id,region_name) values (97,'Libyan Arab Jamahiriya');
INSERT INTO phpgw_weather_region (region_id,region_name) values (98,'Lithuania');
INSERT INTO phpgw_weather_region (region_id,region_name) values (99,'Luxembourg');
INSERT INTO phpgw_weather_region (region_id,region_name) values (100,'Macau');
INSERT INTO phpgw_weather_region (region_id,region_name) values (101,'Madagascar');
INSERT INTO phpgw_weather_region (region_id,region_name) values (102,'Malawi');
INSERT INTO phpgw_weather_region (region_id,region_name) values (103,'Malaysia');
INSERT INTO phpgw_weather_region (region_id,region_name) values (104,'Maldives');
INSERT INTO phpgw_weather_region (region_id,region_name) values (105,'Mali');
INSERT INTO phpgw_weather_region (region_id,region_name) values (106,'Malta');
INSERT INTO phpgw_weather_region (region_id,region_name) values (107,'Marshall Islands');
INSERT INTO phpgw_weather_region (region_id,region_name) values (108,'Martinique');
INSERT INTO phpgw_weather_region (region_id,region_name) values (109,'Mauritania');
INSERT INTO phpgw_weather_region (region_id,region_name) values (110,'Mauritius');
INSERT INTO phpgw_weather_region (region_id,region_name) values (111,'Mexico');
INSERT INTO phpgw_weather_region (region_id,region_name) values (112,'Micronesia, Federated States of');
INSERT INTO phpgw_weather_region (region_id,region_name) values (113,'Morocco');
INSERT INTO phpgw_weather_region (region_id,region_name) values (114,'Mozambique');
INSERT INTO phpgw_weather_region (region_id,region_name) values (115,'Myanmar');
INSERT INTO phpgw_weather_region (region_id,region_name) values (116,'Nauru');
INSERT INTO phpgw_weather_region (region_id,region_name) values (117,'Netherlands');
INSERT INTO phpgw_weather_region (region_id,region_name) values (118,'Netherlands Antilles');
INSERT INTO phpgw_weather_region (region_id,region_name) values (119,'New Caledonia');
INSERT INTO phpgw_weather_region (region_id,region_name) values (120,'New Zealand');
INSERT INTO phpgw_weather_region (region_id,region_name) values (121,'Nicaragua');
INSERT INTO phpgw_weather_region (region_id,region_name) values (122,'Niger');
INSERT INTO phpgw_weather_region (region_id,region_name) values (123,'Norway');
INSERT INTO phpgw_weather_region (region_id,region_name) values (124,'Oman');
INSERT INTO phpgw_weather_region (region_id,region_name) values (125,'Pakistan');
INSERT INTO phpgw_weather_region (region_id,region_name) values (126,'Palau');
INSERT INTO phpgw_weather_region (region_id,region_name) values (127,'Panama');
INSERT INTO phpgw_weather_region (region_id,region_name) values (128,'Paraguay');
INSERT INTO phpgw_weather_region (region_id,region_name) values (129,'Peru');
INSERT INTO phpgw_weather_region (region_id,region_name) values (130,'Philippines');
INSERT INTO phpgw_weather_region (region_id,region_name) values (131,'Poland');
INSERT INTO phpgw_weather_region (region_id,region_name) values (132,'Portugal');
INSERT INTO phpgw_weather_region (region_id,region_name) values (133,'Puerto Rico');
INSERT INTO phpgw_weather_region (region_id,region_name) values (134,'Qatar');
INSERT INTO phpgw_weather_region (region_id,region_name) values (135,'Reunion');
INSERT INTO phpgw_weather_region (region_id,region_name) values (136,'Romania');
INSERT INTO phpgw_weather_region (region_id,region_name) values (137,'Russian Federation');
INSERT INTO phpgw_weather_region (region_id,region_name) values (138,'Rwanda');
INSERT INTO phpgw_weather_region (region_id,region_name) values (139,'Saint Helena');
INSERT INTO phpgw_weather_region (region_id,region_name) values (140,'Saint Kitts and Nevis');
INSERT INTO phpgw_weather_region (region_id,region_name) values (141,'Saint Lucia');
INSERT INTO phpgw_weather_region (region_id,region_name) values (142,'Saint Vincent and the Grenadines');
INSERT INTO phpgw_weather_region (region_id,region_name) values (143,'Samoa');
INSERT INTO phpgw_weather_region (region_id,region_name) values (144,'Sao Tome and Principe');
INSERT INTO phpgw_weather_region (region_id,region_name) values (145,'Saudi Arabia');
INSERT INTO phpgw_weather_region (region_id,region_name) values (146,'Senegal');
INSERT INTO phpgw_weather_region (region_id,region_name) values (147,'Seychelles');
INSERT INTO phpgw_weather_region (region_id,region_name) values (148,'Sierra Leone');
INSERT INTO phpgw_weather_region (region_id,region_name) values (149,'Singapore');
INSERT INTO phpgw_weather_region (region_id,region_name) values (150,'Slovakia');
INSERT INTO phpgw_weather_region (region_id,region_name) values (151,'Slovenia');
INSERT INTO phpgw_weather_region (region_id,region_name) values (152,'Solomon Islands');
INSERT INTO phpgw_weather_region (region_id,region_name) values (153,'Somalia');
INSERT INTO phpgw_weather_region (region_id,region_name) values (154,'South Africa');
INSERT INTO phpgw_weather_region (region_id,region_name) values (155,'Spain');
INSERT INTO phpgw_weather_region (region_id,region_name) values (156,'Sri Lanka');
INSERT INTO phpgw_weather_region (region_id,region_name) values (157,'Sudan');
INSERT INTO phpgw_weather_region (region_id,region_name) values (158,'Suriname');
INSERT INTO phpgw_weather_region (region_id,region_name) values (159,'Swaziland');
INSERT INTO phpgw_weather_region (region_id,region_name) values (160,'Sweden');
INSERT INTO phpgw_weather_region (region_id,region_name) values (161,'Switzerland');
INSERT INTO phpgw_weather_region (region_id,region_name) values (162,'Syrian Arab Republic');
INSERT INTO phpgw_weather_region (region_id,region_name) values (163,'Taiwan');
INSERT INTO phpgw_weather_region (region_id,region_name) values (164,'Tajikistan');
INSERT INTO phpgw_weather_region (region_id,region_name) values (165,'Tanzania, United Republic of');
INSERT INTO phpgw_weather_region (region_id,region_name) values (166,'Thailand');
INSERT INTO phpgw_weather_region (region_id,region_name) values (167,'Togo');
INSERT INTO phpgw_weather_region (region_id,region_name) values (168,'Tonga');
INSERT INTO phpgw_weather_region (region_id,region_name) values (169,'Trinidad and Tobago');
INSERT INTO phpgw_weather_region (region_id,region_name) values (170,'Tunisia');
INSERT INTO phpgw_weather_region (region_id,region_name) values (171,'Turkey');
INSERT INTO phpgw_weather_region (region_id,region_name) values (172,'Tuvalu');
INSERT INTO phpgw_weather_region (region_id,region_name) values (173,'Uganda');
INSERT INTO phpgw_weather_region (region_id,region_name) values (174,'Ukraine');
INSERT INTO phpgw_weather_region (region_id,region_name) values (175,'United Arab Emirates');
INSERT INTO phpgw_weather_region (region_id,region_name) values (176,'United Kingdom');
INSERT INTO phpgw_weather_region (region_id,region_name) values (177,'United States');
INSERT INTO phpgw_weather_region (region_id,region_name) values (178,'United States Minor Outlying Islands');
INSERT INTO phpgw_weather_region (region_id,region_name) values (179,'Uruguay');
INSERT INTO phpgw_weather_region (region_id,region_name) values (180,'Uzbekistan');
INSERT INTO phpgw_weather_region (region_id,region_name) values (181,'Vanuatu');
INSERT INTO phpgw_weather_region (region_id,region_name) values (182,'Venezuela');
INSERT INTO phpgw_weather_region (region_id,region_name) values (183,'Viet Nam');
INSERT INTO phpgw_weather_region (region_id,region_name) values (184,'Virgin Islands, British');
INSERT INTO phpgw_weather_region (region_id,region_name) values (185,'Virgin Islands, U.S.');
INSERT INTO phpgw_weather_region (region_id,region_name) values (186,'Yemen');
INSERT INTO phpgw_weather_region (region_id,region_name) values (187,'Yugoslavia');
INSERT INTO phpgw_weather_region (region_id,region_name) values (188,'Zaire');
INSERT INTO phpgw_weather_region (region_id,region_name) values (189,'Zambia');
INSERT INTO phpgw_weather_region (region_id,region_name) values (190,'Zimbabwe');
