REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'rooms','chat','en','Rooms');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'whowhere','chat','en','Who\'s Where');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'enter chat','chat','en','Enter Chat');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'channels','chat','en','Channels');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'switch room','chat','en','Switch Room');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'part channel','chat','en','Part Channel');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'online','chat','en','Online');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'private chat','chat','en','Private Chat');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'refresh users','chat','en','Refresh Users');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'send message','chat','en','Send Message');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'rooms','chat','cs','Místnosti');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'whowhere','chat','cs','Kdo je kde');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'enter chat','chat','cs','Vstup do chatu');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'channels','chat','cs','Kanály');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'switch room','chat','cs','Zmìò místnost');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'part channel','chat','cs','Part Channel');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'online','chat','cs','Online');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'private chat','chat','cs','Soukromý Chat');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'refresh users','chat','cs','Obnov u¾ivatele');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'send message','chat','cs','Po¹li zprávu');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'rooms','chat','de','R&auml;ume');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'whowhere','chat','de','Wer ist wo');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'enter chat','chat','de','Enter Chat');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'channels','chat','de','Channels');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'switch room','chat','de','Raum wechseln');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'part channel','chat','de','Channel teilen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'online','chat','de','Online');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'private chat','chat','de','Privater Chat');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'refresh users','chat','de','Teilnehmer neu ermitteln');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'send message','chat','de','Nachricht schicken');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'send message','chat','de','Nachricht schicken');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( '','chat','fr','');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( '','chat','kr','');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'rooms','chat','nl','Kamers');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'whowhere','chat','nl','Wie is waar');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'enter chat','chat','nl','Ga Chatten');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'channels','chat','nl','Kanalen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'switch room','chat','nl','Wissel van kamer');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'part channel','chat','nl','Kanaal verlaten');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'online','chat','nl','Beschikbaar');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'private chat','chat','nl','Privé Chat');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'refresh users','chat','nl','Ververs gebruikerslijst');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'send message','chat','nl','Verzend bericht');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'send message','chat','nl','Verzend bericht');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( '','chat','no','');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( '','chat','sp','');
