#!/bin/tcsh -f

if (-d lists) then
  rm -fr lists
endif

mkdir lists

foreach file (tables/*.table)
   set tmpfile = /tmp/`basename ${file}`
   grep "Name" ${file} > ${tmpfile}
   echo 's/&nbsp;/">'`basename ${file} .table`'/' > /tmp/$$.sed
   sed -f /tmp/$$.sed ${tmpfile} > lists/`basename ${file} .table`.list
   rm -f ${tmpfile}
   rm -f /tmp/$$.sed
end
