## istructions to build the image ##
# export INSTALL_MSSQL=true
# export INSTALL_XDEBUG=true
# export INSTALL_ORACLE=true
# docker compose build

services:
  postgres:
    container_name: postgres15_container
    image: postgres:15.0
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - postgres15_volume:/data/postgres
    restart: unless-stopped
  redis:
      container_name: redis_container
      image: redis
      restart: always
      volumes:
       - redisdata:/data
      ports:
        - '6379:6379'
  web:
    container_name: portico_container
    build:
        context: .
        dockerfile: Dockerfile
        args:
           INSTALL_MSSQL: ${INSTALL_MSSQL}
           INSTALL_XDEBUG: ${INSTALL_XDEBUG}
           INSTALL_ORACLE: ${INSTALL_ORACLE:-false}
           http_proxy: ${http_proxy}
           https_proxy: ${https_proxy}
    ports:
      - 8080:80
    environment:
      XDEBUG_CONFIG: client_host=$XDEBUG_IP_ADDRESS
    volumes:
      - ./:/var/www/html/portico/
      - /var/local/:/var/local/
      # developement: store your files in '/var/local/phpgw/<domain>/tmp' and '/var/local/phpgw/<domain>/files'
    restart: always
    depends_on:
      - postgres
      - redis

volumes:
    postgres15_volume:
    redisdata:

