version: '3.6'

services:
  db:
    container_name: postgres_container
    image: postgres:13.1
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    restart: unless-stopped
  mssql:
    container_name: mssql_container
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=ChangeMe10
      - MSSQL_COLLATION="Latin1_General_CS_AI"
      # Note: collation settings here has no effect...
    volumes:
       - sqldata1:/var/opt/mssql
    restart: unless-stopped
  myqsl:
    container_name: mysql_container
    image: mariadb:10.8
    environment:
      MYSQL_ROOT_PASSWORD: ChangeMe10
      MYSQL_DATABASE: mybb
      MYSQL_USER: mybb
      MYSQL_PASSWORD: ChangeMe10
    ports:
      - 3306:3306
    volumes:
       - sqldata2:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_0900_as_cs']
    restart: unless-stopped

  web:
    container_name: portico_container
    image: sigurdne/portico_estate_webserver:latest
#    image: sigurdne/portico_estate_webserver_oracle:latest
    ports:
      - 8080:80
    environment:
      XDEBUG_CONFIG: client_host=$XDEBUG_IP_ADDRESS
    volumes:
      - ./:/var/www/html/portico/
    restart: always
    depends_on:
      - db

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin:/root/.pgadmin
    restart: unless-stopped

volumes:
    postgres:
    pgadmin:
    sqldata1:
    sqldata2:

