<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitf28ace3f3a018e5619ad8d28b51cbc47
{
    public static $prefixLengthsPsr4 = array (
        'j' => 
        array (
            'jamesiarmes\\PhpNtlm\\' => 20,
            'jamesiarmes\\PhpEws\\' => 19,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'jamesiarmes\\PhpNtlm\\' => 
        array (
            0 => __DIR__ . '/..' . '/jamesiarmes/php-ntlm/src',
        ),
        'jamesiarmes\\PhpEws\\' => 
        array (
            0 => __DIR__ . '/..' . '/php-ews/php-ews/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitf28ace3f3a018e5619ad8d28b51cbc47::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitf28ace3f3a018e5619ad8d28b51cbc47::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
