<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInite464cea5e6c61bb054327fddd91b875b
{
    public static $files = array (
        'decc78cc4436b1292c6c0d151b19445c' => __DIR__ . '/..' . '/phpseclib/phpseclib/phpseclib/bootstrap.php',
    );

    public static $prefixLengthsPsr4 = array (
        'p' => 
        array (
            'phpseclib\\' => 10,
        ),
        'L' => 
        array (
            'League\\Flysystem\\Sftp\\' => 22,
            'League\\Flysystem\\' => 17,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'phpseclib\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpseclib/phpseclib/phpseclib',
        ),
        'League\\Flysystem\\Sftp\\' => 
        array (
            0 => __DIR__ . '/..' . '/league/flysystem-sftp/src',
        ),
        'League\\Flysystem\\' => 
        array (
            0 => __DIR__ . '/..' . '/league/flysystem/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInite464cea5e6c61bb054327fddd91b875b::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInite464cea5e6c61bb054327fddd91b875b::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
