[comm] => Array ( 
		 [0] => Array ( 
			       [description] => asddsadsa 
			       [value] => dsadsa 
			       [type] => 
			       [preferred] => on ) 
		 [1] => Array ( 
			       [description] => weewq 
			       [value] => dssadas 
			       [type] => 
			       [preferred] => ) 
		 [2] => Array ( 
			       [description] => vfdhytjyt 
			       [value] => trher 
			       [type] => 
			       [preferred] => )) 