<?php
	/***************************************************************************\
	* phpGroupWare - Workflow                                                     *
	* http://www.phpgroupware.org                                                 *
	* Written by : Regis Leroy [regis.leroy@glconseil.com]                      *
	* -------------------------------------------------                         *
	* This program is free software; you can redistribute it and/or modify it   *
	* under the terms of the GNU General Public License as published by the     *
	* Free Software Foundation; either version 2 of the License, or (at your    *
	* option) any later version.                                                *
	\***************************************************************************/

	class ajaxworkflow
	{
		var $message = array();

		function ajaxworkflow()
		{
		}

		/* test function */
		/* pass an argument and get a description of this arg in a testbox div on your ajax form */
		function test($arg)
		{
			$objResponse = new xajaxResponse();

			if (is_array($arg))
			{
				$newContent = 'array';
			}
			else
			{
				if (is_numeric($arg))
				{
					$newContent = 'a numeric';
				}
				else
				{
					$newContent = 'a text';
				}
			}

			// add a command to the response to assign the innerHTML attribute of
			// the element with id="test" to whatever the new content is
			$objResponse->addAssign("testbox","innerHTML", $newContent);

			//return the XML response generated by the xajaxResponse object
			return $objResponse->getXML();
                }

	}
?>
