= phpGroupWare User's Manual
Brandon Neill
:doctype: article
:encoding: utf-8
:lang: en
:toc: left
:numbered:

[preface]
== Preface
This Manual is for users of phpGroupWare.


== Introduction

What is phpGroupWare

phpGroupWare is a multi-user web-based suite written in PHP. It contains many
applications, including a Calendar, email package, contact database and project
manager. It also includes an extensive API for writing new applications.


=== About the author

Brandon Neill just wanted to figure out how to use the program and decided to
write a manual as an excuse to bug the developers.


=== Acknowledgements

I would like to thank the many authors of phpGroupWare and it's applications
for creating such a useful and extensible product. I would also like to thank
the authors of previous version of the documentation and the authors of the LDP
Author guide for teaching me how to use DocBook.


=== Notes

This document is based upon the current CVS release, where possible I included
notes relating to the current stable release (0.9.12). This is a work in
progress, please email any corrections to <bneill@yahoo.com>.


== General

Here will go an overview of categories and other overall topics.


=== Categories


=== Templates and Themes


=== Access Control Lists


=== Translations


== Calendar

A searchable daily,weekly, monthly calendar/scheduling applicaiton with alerts
for high priority events.



=== Viewing

To view your calendar, click on the calendar icon in the menu. This will bring
you to the default view selected in your preferences. You can click one of the
six icons to change your calendar view.

* [today]Day +
    Current day is displayed, broken down into time increments. Increment and
    working hours can be set in preferences.

* [week]Week +
    Current week is displayed. Start day of week can be set in preferences.

* [month]Month +
    Current month is displayed.

* [year]Year +
    Current year is displayed.

* [planner]Planner +
    I don't know yet

* [view] Daily Matrix View +
    Displays a selection of users and their available times for a given date
    range

=== Adding an entry


=== Editing an entry


=== Preferences


== Email


== Notes



== Todo

A ToDo list application featuring the ability to add project categories and
sub-categories, add ToDo projects and sub-projects, and a gannt chart type
matrix view for pending projects.


=== Viewing

To view your ToDo List, click on the To Do list icon in the menu. This will
bring you to the To Do list main page. From this page you can do the following:

* Category +
    Choose a category to view.

* Show +
    Choose to view all jobs, your jobs, or your private jobs.

* Search +
    Search jobs in the ToDo list.

* Status +
    This is the first column in the table of results. By clicking the "Status"
    link you can sort the ToDo list results by their completion status
    (ascending order). Clicking this link again will reverse the sort
    (descending order).

* Urgency +
    This is the second column in the table of results. By clicking the
    "Urgency" link you can sort the ToDo list results by their Urgency
    (ascending order). Clicking this link again will reverse the sort
    (descending order).

* Title +
    This is the third column in the table of results. By clicking the "Title"
    link you can sort the ToDo list results by their title (ascending order).
    Clicking this link again will reverse the sort (descending order).

* Start Date +
    This is the fourth column in the table of results. By clicking the "Start
    date" link you can sort the ToDo list results by their start date
    (ascending order). Clicking this link again will reverse the sort
    (descending order).

* End Date +
    This is the fifth column in the table of results. By clicking the "End
    date" link you can sort the ToDo list results by their ending date
    (ascending order). Clicking this link again will reverse the sort
    (descending order). Dates for overdue tasks will be displayed in red.

* Created By +
    This is the sixth column in the table of results. By clicking the "Created
    By" link you can sort the ToDo list results by task author (ascending
    order). Clicking this link again will reverse the sort (descending order).

* Add sub +
    This is the seventh column in the table of results. By clicking the "Add
    sub" link on a task or sub-task in the table of results, you can add a
    sub-task to that particular item.

* View +
    This is the eighth column in the table of results. By clicking the "View"
    link on a task or sub-task in the table of results, you can view the
    details of the task.

* Edit +
    This is the ninth column in the table of results. By clicking the "Edit"
    link on a task or sub-task in the table of results, you can edit the
    details of the task.

* Delete +
    This is the tenth column in the table of results. By clicking the "Delete"
    link on a task or sub-task in the table of results, you can delete the
    task.

* Add +
    Clicking the "Add" button will allow you to add a task to the ToDo list.

* View matrix of actual month +
    Clicking the "View matrix of actual month" link will display a gannt chart
    type matrix view of the current month's ToDo list entries.

* Adding +
After clicking the "Add" button on the task results page, you will be presented
with the following options on the "Add Main Project" page:

* Title +
    Enter a title for the task to be added.

* Description +
    Enter a description for the task to be added.

* Parent Project +
    Choose a parent project for the task to be added.

* Start Date +
    Choose a starting date for the task to be added. If the starting date will
    be today, simply check the "select for today" checkbox.

* End Date +
    Choose a Ending Date for the task to be added. Another option is to input
    the number of days from the task start date in the "days from startdate"
    input box.

* Completed +
    Use the drop-down completed box to mark the approximate completion status
    for the task to be added.

* Urgency +
    Use the drop-down Urgency box to choose between low, normal, and high
    urgency settings for the task to be added.

* Private +
    Check the "Private" checkbox to make this task viewable only by you.

* Category +
    Choose a category for the task to be added.

* Submit +
    Click the "Submit" button to add this task to the ToDo list.

* Clear Form +
    Click the "Clear Form" button to reset the form to its default (empty)
    state.


* Add sub +
After clicking the "Add sub" link on the task results page, you will be
presented with the following options on the "Add sub project" page:


== Project


== File Manager

