#!/bin/tcsh -f

if (-d tables) then
  rm -fr tables
endif

mkdir tables

touch /tmp/$$.sed

foreach table (`./get_table_names`)
   set tabletype = `echo $table | sed 's/#//;y/-/_/'`
   echo '/'$table'"/,/<\/TABLE>/{' >> /tmp/$$.sed
   echo "w tables/"$tabletype".table" >> /tmp/$$.sed
   echo "}" >> /tmp/$$.sed
end

sed -f /tmp/$$.sed details > /dev/null

rm -f /tmp/$$.sed
