INSERT INTO phpgw_us_states values (1,'','Not Applicable');
INSERT INTO phpgw_us_states values (2,'AL','Alabama');
INSERT INTO phpgw_us_states values (3,'AK','Alaska');
INSERT INTO phpgw_us_states values (4,'AZ','Arizona');
INSERT INTO phpgw_us_states values (5,'AR','Arkansas');
INSERT INTO phpgw_us_states values (6,'CA','California');
INSERT INTO phpgw_us_states values (7,'CO','Colorado');
INSERT INTO phpgw_us_states values (8,'CT','Connecticut');
INSERT INTO phpgw_us_states values (9,'DE','Delaware');
INSERT INTO phpgw_us_states values (10,'FL','Florida');
INSERT INTO phpgw_us_states values (11,'GA','Georgia');
INSERT INTO phpgw_us_states values (12,'HI','Hawaii');
INSERT INTO phpgw_us_states values (13,'ID','Idaho');
INSERT INTO phpgw_us_states values (14,'IL','Illinois');
INSERT INTO phpgw_us_states values (15,'IN','Indiana');
INSERT INTO phpgw_us_states values (16,'IA','Iowa');
INSERT INTO phpgw_us_states values (17,'KS','Kansas');
INSERT INTO phpgw_us_states values (18,'KY','Kentucky');
INSERT INTO phpgw_us_states values (19,'LA','Louisiana');
INSERT INTO phpgw_us_states values (20,'ME','Maine');
INSERT INTO phpgw_us_states values (21,'MD','Maryland');
INSERT INTO phpgw_us_states values (22,'MA','Massachusetts');
INSERT INTO phpgw_us_states values (23,'MI','Michigan');
INSERT INTO phpgw_us_states values (24,'MN','Minnesota');
INSERT INTO phpgw_us_states values (25,'MS','Mississippi');
INSERT INTO phpgw_us_states values (26,'MO','Missouri');
INSERT INTO phpgw_us_states values (27,'MT','Montana');
INSERT INTO phpgw_us_states values (28,'NE','Nebraska');
INSERT INTO phpgw_us_states values (29,'NV','Nevada');
INSERT INTO phpgw_us_states values (30,'NH','New Hampshire');
INSERT INTO phpgw_us_states values (31,'NJ','New Jersey');
INSERT INTO phpgw_us_states values (32,'NM','New Mexico');
INSERT INTO phpgw_us_states values (33,'NY','New York');
INSERT INTO phpgw_us_states values (34,'NC','North Carolina');
INSERT INTO phpgw_us_states values (35,'ND','North Dakota');
INSERT INTO phpgw_us_states values (36,'OH','Ohio');
INSERT INTO phpgw_us_states values (37,'OK','Oklahoma');
INSERT INTO phpgw_us_states values (38,'OR','Oregon');
INSERT INTO phpgw_us_states values (39,'PA','Pennsylvania');
INSERT INTO phpgw_us_states values (40,'RI','Rhode Island');
INSERT INTO phpgw_us_states values (41,'SC','South Carolina');
INSERT INTO phpgw_us_states values (42,'SD','South Dakota');
INSERT INTO phpgw_us_states values (43,'TN','Tennessee');
INSERT INTO phpgw_us_states values (44,'TX','Texas');
INSERT INTO phpgw_us_states values (45,'UT','Utah');
INSERT INTO phpgw_us_states values (46,'VT','Vermont');
INSERT INTO phpgw_us_states values (47,'VA','Virginia');
INSERT INTO phpgw_us_states values (48,'WA','Washington');
INSERT INTO phpgw_us_states values (49,'DC','Washington DC');
INSERT INTO phpgw_us_states values (50,'WV','West Virginia');
INSERT INTO phpgw_us_states values (51,'WI','Wisconsin');
INSERT INTO phpgw_us_states values (52,'WY','Wyoming');
