#!/bin/tcsh -f

./create_tables
./create_lists
./create_csv

if (-d sql) then
   rm -fr sql
endif

mkdir sql

foreach file (csv/*)
  set tmpfile = `basename ${file} .csv`
  awk -v db=${tmpfile} 'BEGIN{FS=";";printf "INSERT INTO phpgw_mediadb_%s (role, movieid, artistid)", db;reentry=0;} {if(reentry > 0) printf ","; reentry++; printf "\n\tVALUES (\"%s\", \"XXX\", \"%s\")", $2, $1} END{printf "\n"}' ${file} > sql/${tmpfile}.sql
end
rm -fr tables lists csv
