<?php
	/**
	 * soap client for http://geomatikk.no/ braArkiv
	 * this code is generated by the https://github.com/mikaelcom/WsdlToPhp/
	 * File to load generated classes once at once time
	 * @package Bra5
	 * @date 2015-03-06
	 */

/**
 * Includes for all generated classes files
 * @date 2015-03-06
 */
require_once dirname(__FILE__) . '/Bra5WsdlClass.php';
require_once dirname(__FILE__) . '/Document/Bra5StructDocument.php';
require_once dirname(__FILE__) . '/Delete/Response/Bra5StructDeleteDocumentResponse.php';
require_once dirname(__FILE__) . '/Delete/Document/Bra5StructDeleteDocument.php';
require_once dirname(__FILE__) . '/Get/Name/Bra5StructGetFileName.php';
require_once dirname(__FILE__) . '/Update/Response/Bra5StructUpdateAttributeResponse.php';
require_once dirname(__FILE__) . '/Get/Response/Bra5StructGetFileNameResponse.php';
require_once dirname(__FILE__) . '/Array/Document/Bra5StructArrayOfExtendedDocument.php';
require_once dirname(__FILE__) . '/Search/Documents/Bra5StructSearchAndGetDocuments.php';
require_once dirname(__FILE__) . '/Update/Attribute/Bra5StructUpdateAttribute.php';
require_once dirname(__FILE__) . '/Update/Document/Bra5StructUpdateDocument.php';
require_once dirname(__FILE__) . '/Get/Response/Bra5StructGetDocumentResponse.php';
require_once dirname(__FILE__) . '/Array/Variant/Bra5StructArrayOfVariant.php';
require_once dirname(__FILE__) . '/Variant/Bra5StructVariant.php';
require_once dirname(__FILE__) . '/Extended/Document/Bra5StructExtendedDocument.php';
require_once dirname(__FILE__) . '/Get/Attribute/Bra5StructGetAttribute.php';
require_once dirname(__FILE__) . '/Search/Response/Bra5StructSearchAndGetDocumentsResponse.php';
require_once dirname(__FILE__) . '/Get/Response/Bra5StructGetAttributeResponse.php';
require_once dirname(__FILE__) . '/Update/Response/Bra5StructUpdateDocumentResponse.php';
require_once dirname(__FILE__) . '/Put/Array/Bra5StructPutFileAsByteArray.php';
require_once dirname(__FILE__) . '/File/Chunk/Bra5StructFileTransferRequestChunk.php';
require_once dirname(__FILE__) . '/File/Response/Bra5StructFileTransferRequestChunkedInitResponse.php';
require_once dirname(__FILE__) . '/File/Init/Bra5StructFileTransferRequestChunkedInit.php';
require_once dirname(__FILE__) . '/File/Response/Bra5StructFileTransferRequestChunkResponse.php';
require_once dirname(__FILE__) . '/File/End/Bra5StructFileTransferRequestChunkedEnd.php';
require_once dirname(__FILE__) . '/Get/Response/Bra5StructGetArchiveNameResponse.php';
require_once dirname(__FILE__) . '/Get/Name/Bra5StructGetArchiveName.php';
require_once dirname(__FILE__) . '/File/Response/Bra5StructFileTransferRequestChunkedEndResponse.php';
require_once dirname(__FILE__) . '/File/Response/Bra5StructFileTransferSendChunkedEndResponse.php';
require_once dirname(__FILE__) . '/File/End/Bra5StructFileTransferSendChunkedEnd.php';
require_once dirname(__FILE__) . '/Get/Response/Bra5StructGetFileAsByteArrayResponse.php';
require_once dirname(__FILE__) . '/Get/Array/Bra5StructGetFileAsByteArray.php';
require_once dirname(__FILE__) . '/Put/Response/Bra5StructPutFileAsByteArrayResponse.php';
require_once dirname(__FILE__) . '/File/Init/Bra5StructFileTransferSendChunkedInit.php';
require_once dirname(__FILE__) . '/File/Response/Bra5StructFileTransferSendChunkedInitResponse.php';
require_once dirname(__FILE__) . '/File/Response/Bra5StructFileTransferSendChunkResponse.php';
require_once dirname(__FILE__) . '/File/Chunk/Bra5StructFileTransferSendChunk.php';
require_once dirname(__FILE__) . '/Get/Document/Bra5StructGetDocument.php';
require_once dirname(__FILE__) . '/Create/Response/Bra5StructCreateDocumentResponse.php';
require_once dirname(__FILE__) . '/Get/Classes/Bra5StructGetAvailableClasses.php';
require_once dirname(__FILE__) . '/Document/Type/Bra5StructDocumentSplitType.php';
require_once dirname(__FILE__) . '/Array/Type/Bra5StructArrayOfDocumentSplitType.php';
require_once dirname(__FILE__) . '/Get/Response/Bra5StructGetAvailableClassesResponse.php';
require_once dirname(__FILE__) . '/Array/Privilege/Bra5StructArrayOfDocumentClassPrivilege.php';
require_once dirname(__FILE__) . '/Get/URL/Bra5StructGetRelativeFileURL.php';
require_once dirname(__FILE__) . '/Document/Privilege/Bra5StructDocumentClassPrivilege.php';
require_once dirname(__FILE__) . '/Get/Response/Bra5StructGetDocumentSplitTypesResponse.php';
require_once dirname(__FILE__) . '/Get/Types/Bra5StructGetDocumentSplitTypes.php';
require_once dirname(__FILE__) . '/Logout/Response/Bra5StructLogoutResponse.php';
require_once dirname(__FILE__) . '/Logout/Bra5StructLogout.php';
require_once dirname(__FILE__) . '/Login/Response/Bra5StructLoginResponse.php';
require_once dirname(__FILE__) . '/Get/Lines/Bra5StructGetProductionLines.php';
require_once dirname(__FILE__) . '/Get/Response/Bra5StructGetProductionLinesResponse.php';
require_once dirname(__FILE__) . '/Production/Line/Bra5StructProductionLine.php';
require_once dirname(__FILE__) . '/Array/Line/Bra5StructArrayOfProductionLine.php';
require_once dirname(__FILE__) . '/Get/Response/Bra5StructGetRelativeFileURLResponse.php';
require_once dirname(__FILE__) . '/Get/Attributes/Bra5StructGetAvailableAttributes.php';
require_once dirname(__FILE__) . '/Get/Response/Bra5StructGetLookupValuesResponse.php';
require_once dirname(__FILE__) . '/Array/Value/Bra5StructArrayOfLookupValue.php';
require_once dirname(__FILE__) . '/Get/Values/Bra5StructGetLookupValues.php';
require_once dirname(__FILE__) . '/Search/Document/Bra5StructSearchDocument.php';
require_once dirname(__FILE__) . '/Array/String/Bra5StructArrayOfString.php';
require_once dirname(__FILE__) . '/Create/Document/Bra5StructCreateDocument.php';
require_once dirname(__FILE__) . '/Search/Response/Bra5StructSearchDocumentResponse.php';
require_once dirname(__FILE__) . '/Address/Bra5StructAddress.php';
require_once dirname(__FILE__) . '/Pair/Bra5StructPair.php';
require_once dirname(__FILE__) . '/Attribute/Bra5StructAttribute.php';
require_once dirname(__FILE__) . '/Array/Attribute/Bra5StructArrayOfAttribute.php';
require_once dirname(__FILE__) . '/Get/Response/Bra5StructGetAvailableAttributesResponse.php';
require_once dirname(__FILE__) . '/Bra/Type/Bra5EnumBraArkivAttributeType.php';
require_once dirname(__FILE__) . '/Array/Type/Bra5StructArrayOfAnyType.php';
require_once dirname(__FILE__) . '/Matrikkel/Bra5StructMatrikkel.php';
require_once dirname(__FILE__) . '/Lookup/Value/Bra5StructLookupValue.php';
require_once dirname(__FILE__) . '/Login/Bra5StructLogin.php';
require_once dirname(__FILE__) . '/Login/Bra5ServiceLogin.php';
require_once dirname(__FILE__) . '/Logout/Bra5ServiceLogout.php';
require_once dirname(__FILE__) . '/Get/Bra5ServiceGet.php';
require_once dirname(__FILE__) . '/Search/Bra5ServiceSearch.php';
require_once dirname(__FILE__) . '/Create/Bra5ServiceCreate.php';
require_once dirname(__FILE__) . '/Update/Bra5ServiceUpdate.php';
require_once dirname(__FILE__) . '/Delete/Bra5ServiceDelete.php';
require_once dirname(__FILE__) . '/Put/Bra5ServicePut.php';
require_once dirname(__FILE__) . '/File/Bra5ServiceFile.php';
require_once dirname(__FILE__) . '/Bra5ClassMap.php';
