<center><h3>{title}</h3></center>

<form method="POST" name="{formname}" action="{postlink}">
<center>
<table border=0 width=65%>
<tr>
  <td>{company_label}</td><td>{company_display}</td>
</tr>
<tr>
  <td>{contact_label}</td><td>{contact_display}</td>
</tr>
<tr>
  <td>{assigned_label}</td><td>{assigned_display}</td>
</tr>
<tr>
  <td>{jobnum_label}</td><td>{jobnum_display}</td>
</tr>
<tr>
  <td>{summary_label}</td><td>{summary_display}</td>
</tr>
<tr>
  <td>{detail_label}</td><td>{detail_display}</td>
</tr>
<tr>
  <td>{quotedate_label}</td><td>{quotedate_display}</td>
</tr>
<tr>
  <td>{quotehours_label}</td><td>{quotehours_display}</td>
</tr>
<tr>
  <td>{opendate_label}</td><td>{opendate_display}</td>
</tr>
<tr>
  <td>{deadline_label}</td><td>{deadline_display}</td>
</tr>
<tr>
  <td>{manager_label}</td><td>{manager_display}</td>
</tr>
<tr>
  <td>{status_label}</td><td>{status_display</td>
</tr>
<tr>
  <td>{billable_label}</td><td>{billable_display}</td>
</tr>
<tr>
  <td colspan=2>{submit_bar}</td>
</tr>
</table>
</center>
</form>
