DELETE FROM lang WHERE app_name='eldaptir';
DELETE FROM lang WHERE message_id='eldaptir';
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'eldaptir','common','en','eLDAPtir');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'eldaptir','common','de','eLDAPtir');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'data','eldaptir','en','data');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'data','eldaptir','de','daten');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'empty','eldaptir','en','empty');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'empty','eldaptir','de','leer');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'required','eldaptir','en','required');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'required','eldaptir','de','erfordert');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'optional','eldaptir','en','optional');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'optional','eldaptir','de','wahlweise');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'ldap browser','eldaptir','en','LDAP Browser');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'ldap browser','eldaptir','de','LDAP Browser');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'browser','eldaptir','en','Browser');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'browser','eldaptir','de','Browser');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'browse','eldaptir','en','Browse');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'browse','eldaptir','de','Browse');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'common items','eldaptir','en','Common Items');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'common items','eldaptir','de','Common Items');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'organizational units','eldaptir','en','Organizational Units');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'organizational units','eldaptir','de','Organizational Units');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'objectclass','eldaptir','en','Objectclass');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'objectclass','eldaptir','de','Objectclass');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'attribute','eldaptir','en','Attribute');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'attribute','eldaptir','de','Attribute');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'value','eldaptir','en','Value');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'value','eldaptir','de','Value');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'rule','eldaptir','en','Rule');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'rule','eldaptir','de','Rule');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'server x has been added','eldaptir','en','Server %1 has been added');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'server x has been added','eldaptir','de','Server %1 has been added');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'view ou','eldaptir','en','View OU');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'view ou','eldaptir','de','View OU');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'ldap servers','eldaptir','en','LDAP Servers');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'ldap servers','eldaptir','de','LDAP Servers');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'edit server','eldaptir','en','Edit Server');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'edit server','eldaptir','de','Edit Server');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'add ldap server','eldaptir','en','Add LDAP Server');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'add ldap server','eldaptir','de','Add LDAP Server');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'basedn','eldaptir','en','Base DN');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'basedn','eldaptir','de','Base DN');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'rootdn','eldaptir','en','Root DN');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'rootdn','eldaptir','de','Root DN');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'server name','eldaptir','en','Server Name');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'server name','eldaptir','de','Server Name');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'server rootdn','eldaptir','en','Server Root DN');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'server rootdn','eldaptir','de','Server Root DN');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'server rootpw','eldaptir','en','Server Root PW');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'server rootpw','eldaptir','de','Server Root PW');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'server basedn','eldaptir','en','Server Base DN');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'server basedn','eldaptir','de','Server Base DN');

INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'cn','eldaptir','br','cn');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'cn','eldaptir','cs','cn');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'cn','eldaptir','de','cn');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'cn','eldaptir','en','cn');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'cn','eldaptir','fr','cn');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'cn','eldaptir','kr','cn');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'cn','eldaptir','nl','cn');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'cn','eldaptir','sp','cn');

INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'dn','eldaptir','br','dn');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'dn','eldaptir','cs','dn');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'dn','eldaptir','de','dn');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'dn','eldaptir','en','dn');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'dn','eldaptir','fr','dn');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'dn','eldaptir','kr','dn');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'dn','eldaptir','nl','dn');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'dn','eldaptir','sp','dn');

INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'sn','eldaptir','br','sn');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'sn','eldaptir','cs','sn');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'sn','eldaptir','de','sn');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'sn','eldaptir','en','sn');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'sn','eldaptir','fr','sn');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'sn','eldaptir','kr','sn');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'sn','eldaptir','nl','sn');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'sn','eldaptir','sp','sn');

INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'givenname','eldaptir','br','givenname');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'givenname','eldaptir','cs','givenname');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'givenname','eldaptir','de','givenname');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'givenname','eldaptir','en','givenname');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'givenname','eldaptir','fr','givenname');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'givenname','eldaptir','kr','givenname');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'givenname','eldaptir','nl','givenname');
INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'givenname','eldaptir','sp','givenname');

